### ISSUE TITLE
Добавить обработку аргументов в методах/конструкторах

### ISSUE THREAD

**Issue by AlphaBeth** [neevink/programming-lab4#6]
Исключения можно (и нужно) использовать для того, чтобы как можно раньше предотвратить некорректное поведение программы вследствие её неправильного использования. Например, может ли имя персонажа быть null? Я подозреваю, что нет. А в конструктор можно передать null, и обнаружится это только при дальнейшем использовании созданного персонажа.

Для таких ошибок можно использовать как стандартные исключения java (NullPointerException, IllegalArgumentException и прочие), так и сделать собственные (и унаследовать их от стандартных, например).

**Comment by neevink** [comment]
Прошёлся по всем конструкторам и методам, добавил исключения.

**Comment by AlphaBeth** [comment]
https://github.com/neevink/programming-lab4/blob/91de6ef90a92c6081b9ebe8f9f797076fd90b269/src/com/neevin/characters/BookCharacter.java#L30
1. Обрабатывать по отдельности каждое поле
2. Добавить сообщение, по которому будет понятно, что не так.

**Comment by neevink** [comment]
Создал класс ExceptionHelper, а в нём статик-методы, которые выбрасывают исключения. Прошёлся по всем методам и конструкторам - исправил косяки, теперь всё красиво.
