### ISSUE TITLE
Лучше всё-таки фабричный метод

### ISSUE THREAD

**Issue by AlphaBeth** [neevink/programming-lab4#7]
https://github.com/neevink/programming-lab4/blob/b2c7c3e332bb070a0eb68ef8f845946fd3c3c740/src/com/neevin/misc/Signature.java#L40-L44

Просто в данном варианте выглядит так, будто у персонажей есть сама подпись (на клочке бумаги, набита татуха или мало ли ещё как), что выглядит странно.

Кстати, фабричный метод очень хорошо ложится на требование использования анонимных классов в вашей программе - под каждый фабричный метод можно будет завести анонимный класс.

**Comment by neevink** [comment]
BookCharacter теперь имеет новое поле-объект класса, который, реализует ISignatureMaker. Таким образом в конструкторе можно передать анонимный класс с методом, который говорит как именно делать подпись.
