### ISSUE TITLE
Сделайте явную связь с тем, что они захлопали из-за того, что они услышали резолюцию.

### ISSUE THREAD

**Issue by AlphaBeth** [neevink/programming-lab4#8]
https://github.com/neevink/programming-lab4/blob/b2c7c3e332bb070a0eb68ef8f845946fd3c3c740/src/com/neevin/Main.java#L53-L56

Сейчас резолюцию на самом деле никто не слышит - она просто выводится в консоль. А на самом деле есть кто-то, кто её слышит, это влияет на их настроение. И конкретно эта резолюция им настроение подняла, так что им захотелось захлопать, потому когда им предложили хлопать - они хлопали.

**Comment by neevink** [comment]
Пофиксил. Теперь появился класс Phrase, который содержит текст фразы и анонимный класс с методом(как повлияет на персонажа эта фраза). Также теперь фразу можно говорить одному или нескольким персонажам одновременно.
